entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  file:
    directory: "/domains"
    watch: true

certificatesResolvers:
  myresolver:
    acme:
      email: danfestudio@outlook.com
      storage: "acme.json"
      httpChallenge:
        entryPoint: "web"